services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    env_file:
      - ../secrets.env
      - ../general.env
      - .env
    ports:
      - 7421:80
    volumes:
      - ./data:/data
    restart: unless-stopped
