services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    env_file:
      - ../secrets.env
      - ../general.env
      - .env
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
