- name: Videos
  columns:
    - size: full
      widgets:
        - type: videos
          title: 🎾 Tennis
          playlists:
            - PL2RR--XMozwUSJpVJYe5-4gXt-nlUmlWH  # Australian Open
            - PLUK9NdagG_CdWAYIhiBoWIPayUntnC-F9  # Roland-Garros
            - PLwx9gNibGUz70mC4ZPJgE2Ibw0zGGxEdZ  # Wimbledon
            - PL_2A0MxHOgdbPld7FYq1heHGrZjhUEkYU  # Us Open

        - type: videos
          title: 🏎️ Formula 1
          channels:
            - UCB_qr75-ydFVKSF9Dmo6izg  # Formula 1

        - type: videos
          title: 📼 Other
          channels:
            - UCBJycsmduvYEL83R_U4JriQ  # Marques Brownlee
            - UC-lHJZR3Gqxm24_Vd_AJ5Yw  # PewDiePie
            - UC9x0AN7BWHpCDHSm9NiJFJQ  # NetworkChuck

    - size: small
      widgets:
        - type: custom-api
          title: Next Race
          cache: 2h
          url: https://f1api.dev/api/current/next
          template: |
            <div class="flex flex-column gap-10">
              {{ $session := index (.JSON.Array "race") 0 }}
              <p class="size-h5">
                Round {{ .JSON.String "round" }}
              </p>
            
              <div class="margin-block-4">
                <p class="color-highlight">{{ $session.String "raceName" }}</p>
                <p class="color-primary">
                  <span>Race</span>
                  {{ $datetime := concat ($session.String "schedule.race.date") "T" ($session.String "schedule.race.time") }}
                  <span
                    class="color-highlight"
                    title="{{ $session.String "schedule.race.date" }}"
                    {{ parseRelativeTime "rfc3339" $datetime }}
                  ></span>
                </p>
                <p class="size-h5">{{ $session.String "schedule.race.date" }} at {{ $session.String "schedule.race.time" }}</p>
              </div>
            
              <ul class="size-h5 attachments">
                <li>{{ $session.String "circuit.country" }}</li>
                <li>{{ $session.String "circuit.city" }}</li>
                <li>{{ $session.String "circuit.circuitName" }}</li>
              </ul>
            </div>

        - type: twitch-channels
          channels:
            - lirik
            - bobross
            - pewdiepie
