services:
  glance:
    image: glanceapp/glance
    container_name: glance
    volumes:
      - ${FLEET_PATH}/glance/config:/app/config
      - ${FLEET_PATH}/glance/assets:/app/assets
    ports:
      - 6743:8080
    restart: unless-stopped
