services:
  glance:
    image: glanceapp/glance
    container_name: glance
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    ports:
      - 6743:8080
    restart: unless-stopped
