networks:
  fleet:
    external: true

services:
  glance:
    image: glanceapp/glance
    container_name: glance
    volumes:
      - ${GLANCE_PATH:-.}/config:/app/config
      - ${GLANCE_PATH:-.}/assets:/app/assets
    ports:
      - 6743:8080
    networks:
      - fleet
    restart: unless-stopped

  forge:
    image: ghcr.io/drejleeo/forge:main
    container_name: forge
    networks:
      - fleet
    restart: unless-stopped
